apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-writer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: email-writer
  template:
    metadata:
      labels:
        app: email-writer
    spec:
      containers:
        - name: email-writer
          image: imranariff/demo-email-springboot:1.0
          ports:
            - containerPort: 8080
          env:
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-secret
                  key: GEMINI_API_KEY
            - name: GEMINI_API_URL
              valueFrom:
                secretKeyRef:
                  name: ai-secret
                  key: GEMINI_API_URL



